### ISSUE TITLE
Defining complex np.array

### ISSUE THREAD

**Issue by miamico** [rupeshknn/lanczos-QD#1]
https://github.com/rupeshknn/lanczos-QD/blob/c4bef7866ef8a80d5f2c1fc6791b0d1d930f8133/spinchain.py#L15

If the goal here is to make the np.array a complex array, you can directly define it as complex using:
`np.array([[0, 1], [1, 0]], dtype = complex)`

**Comment by rupeshknn** [comment]
fixed in [03f6eea](https://github.com/rupeshknn/lanczos-QD/commit/03f6eea6e7a361c0730052e6231b6c9b48ddd04f)
